### ISSUE TITLE
TiDB arm64 and amd64 docker images differ in used OS and installed tools

### ISSUE THREAD

**Issue by kbanka** [PingCAP-QE/ci#1001]
Current Arm64 TiDB docker image is based on CentOS (glibc) distribution, while Amd64 is based on Alpine (musl). Because of that, we have quite different runtime environment available depending on system architecture we're running at.
This makes it harder to maintain the same build steps on top of these images (eg. installing additional packages with either `dnf` or `apk`). It also makes it hard to use TiDB in local dev environments based on docker_compose, where we've used to use netcat (on Alpine amd64 images) for checking container readiness, while it is not available on arm64 image, where we use now virtual (/dev/tcp/$host/$port) device to establish "ping" communication.

This ticket is related to https://github.com/PingCAP-QE/ci/issues/693 but covers different area - runtime environment skew.

**Comment by lijie0123** [comment]
in 6.6, all image will based on rocky

**Comment by wuhuizuo** [comment]
finished. We can close it.
