### ISSUE TITLE
ticdc ci pipeline not update latest commit on pr 

### ISSUE THREAD

**Issue by purelind** [PingCAP-QE/ci#1204]
repo tiflow, ticdc cipieline

CI pipeline not update status to latest pr commit after comment /run-all-test on pr .

example
https://github.com/pingcap/tiflow/pull/6464#issuecomment-1196336446
1. webhook on github send to jenkins correctly
2. jenkins receive webhook request then trigger pipeline with the wrong commit id(not the latest commit on pr)

**Comment by wuhuizuo** [comment]
Now tiflow use prow style jobs, prow will update the github context status for CI jobs.
