### ISSUE TITLE
bug: gethash.py won't fail when 404

### ISSUE THREAD

**Issue by lijie0123** [PingCAP-QE/ci#1577]

**Comment by wuhuizuo** [comment]
https://cd.pingcap.net/blue/organizations/jenkins/pre-release-tiup/detail/pre-release-tiup/556/pipeline/11

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/2574558/203691514-4022e2e7-f691-4d47-9aaf-c399de542c36.png">
