### ISSUE TITLE
tiflow verify ci uploads codecov report to wrong repo

### ISSUE THREAD

**Issue by amyangfei** [PingCAP-QE/ci#1647]
Given a sample pipeline: https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftiflow%2Fghpr_verify/detail/ghpr_verify/878/pipeline/164

The coverage report was uploaded to `pingcap/dm`

```
    -> Reports have been successfully queued for processing at https://app.codecov.io/github/pingcap/dm/commit/0200ec56551e7d12ae5755bb5d8bcc5e39a8c8d6
```

Did we use the correct token for `TICDC_CODECOV_TOKEN`, seems there is no other configuration.

**Comment by purelind** [comment]
currently using the token of the dm repo incorrectly, i will fix this
