### ISSUE TITLE
Failed to extract logs when tiflash integration test failed

### ISSUE THREAD

**Issue by hongyunyan** [PingCAP-QE/ci#2021]
When tiflash's integration test failed, ci can't successfully extract log files, so we can not get the enough information about the process, which make debug toughly. 
such as https://ci.pingcap.net/blue/organizations/jenkins/tiflash-ghpr-integration-tests/detail/tiflash-ghpr-integration-tests/12480/pipeline

<img width="1324" alt="image" src="https://user-images.githubusercontent.com/2574558/233249248-d8c7b74c-7d2e-4d1a-96be-cc30dbb037ec.png">
<img width="648" alt="image" src="https://user-images.githubusercontent.com/2574558/233249303-e2e72dff-358c-4f30-860b-3a59c4d1d372.png">

**Comment by windtalker** [comment]
I also encounter this problem :(

**Comment by JaySon-Huang** [comment]
+1
