### ISSUE TITLE
The command matching rules for triggering tests in the tiflow repository are too strict and often fail to trigger.

### ISSUE THREAD

**Issue by asddongmen** [PingCAP-QE/ci#2147]
![image](https://github.com/PingCAP-QE/ci/assets/20351731/f4112b87-e6a7-4b25-9f1a-aa964a4b33cc)
As shown in the above figure, I cannot trigger the corresponding CI using `/test cdc-integration-kafka-test`, and it is difficult to tell from the naked eye where I went wrong.

Sometimes I directly copy the command suggested by tichibot and still encounter similar issues.

PR link:https://github.com/pingcap/tiflow/pull/9138

**Comment by wuhuizuo** [comment]
caused by: https://github.com/ti-community-infra/test-infra/blob/release/prow/plugins/trigger/generic-comment.go#L129
