### ISSUE TITLE
Some multi-branch build pipeline optimization directions

### ISSUE THREAD

**Issue by purelind** [PingCAP-QE/ci#2194]
The [current pipelines](https://github.com/PingCAP-QE/ci/tree/main/jenkins/pipelines/cd/multibranch) have their own compilation logic. We should use build-common and docker-common consistently to reduce maintenance costs.
Other areas for improvement.

* Only respond to automatic triggers from active branches, Does not respond to events from the hotfix branch.
* Specify the upload path and packaging components for standardized products, clearly define the usage scenarios of binary artifacts and images.

**Comment by wuhuizuo** [comment]
Let us switch to the new CD. We will not solve it in old Jenkins jobs.
