### ISSUE TITLE
Only members under the organization can be invited after /cherry-pick-invite

### ISSUE THREAD

**Issue by purelind** [PingCAP-QE/ci#2205]
<img width="953" alt="image" src="https://github.com/PingCAP-QE/ci/assets/16618216/0cfe6d58-8cf9-438e-94a8-954b7463d1ae">

**Comment by wuhuizuo** [comment]
I think we should use chatOps bot to reach it for community security.

**Comment by wuhuizuo** [comment]
If any one need it, can ask the bot self or EE help he o her.

**Comment by wuhuizuo** [comment]
We have fixed it in inner IM channel.
