### ISSUE TITLE
tidb-test: ghpr_integration_mysql_test support specify pd & tikv version to download and test

### ISSUE THREAD

**Issue by wuhuizuo** [PingCAP-QE/ci#2207]
https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb-test%2Frelease-6.2%2Fghpr_integration_mysql_test/detail/ghpr_integration_mysql_test/24/pipeline/80

same support with ci params in title as `tidb`.

**Comment by wuhuizuo** [comment]
<img width="1494" alt="image" src="https://github.com/PingCAP-QE/ci/assets/2574558/91119bdc-10f6-43b3-b3cb-85844fb0ba7c">

**Comment by purelind** [comment]
pd & tikv use the default branch, so we turn it off.
