### ISSUE TITLE
Support for manually triggering the integration testing pipeline on tidb PR 

### ISSUE THREAD

**Issue by purelind** [PingCAP-QE/ci#2233]
Currently some prow postsumit jobs will auto run after each PR merged. In order to conveniently run integration tests in PR, need to support PR triggering for these integrated testing pipelines.

- [x] pull-integration-mysql-test
- [x] pull-br-integration-test
- [x] pull-e2e-test
- [x] pull-integration-jdbc-test
- [x] pull-integration-copr-test
- [x] pull-common-test
- [x] pull-integration-common-test
- [x] pull-integration-ddl-test
- [x] pull-sqllogic-test
- [x] pull-tiflash-test

**Comment by wuhuizuo** [comment]
Any updates?
