### ISSUE TITLE
Prioritize more integration testing pipelines before merging PRs on tidb

### ISSUE THREAD

**Issue by purelind** [PingCAP-QE/ci#2398]
Now, before merging a PR in the tidb repository, several pipelines are triggered to validate and ensure the quality of the PR. These pipelines typically consume fewer resources and have shorter execution times.
* build
* unit-test
* check
* check_dev2
* mysql-test

Meanwhile, after the PR merge, more integration testing pipelines will be triggered based on the newly merged commit to ensure the code quality of the master branch. These integrated tests typically have high concurrency, require significant resources, and take a relatively long time to execute.
* integration-br-test
* mysql-connector-test
* integration-sequelize-test
* integration-prisma-test
* integration-python-orm-test
* tiflash-test
* integration-copr-test
* sqllogic-test
* integration-mysql-test
* integration-jdbc-test
* integration-ddl-test
* integration-common-test
* common-test
* e2e-test

For the pipelines that must be run before merging PRs, in order to ensure efficiency and user experience of PR merging, we have put forward the following requirements.
* The stability of test cases is extremely important. The stability of testing should not be lower than 95%. Unstable test cases need to be fixed within one day.
* Reasonable resource consumption, it is recommended to not exceed 8 cores and 16GB for resource allocation.
* The execution time should be reasonable, preferably less than 15 minutes. If it exceeds half an hour, the development experience will significantly decrease.

**Comment by wuhuizuo** [comment]
@purelind 
Any updates?
if it is not finished, please move it to next milestone.

**Comment by wuhuizuo** [comment]
done
