### ISSUE TITLE
Rust toolchains installation is too slow

### ISSUE THREAD

**Issue by skyzh** [PingCAP-QE/ci#244]
It may take ~7min to install Rust toolchains.

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/4198311/120300090-30bb6000-c2fe-11eb-9628-e5b02f104f2d.png">

In https://github.com/PingCAP-QE/ci/blob/main/jenkins/Dockerfile/centos7_golang-1.13_rust

```
RUN curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path --default-toolchain nightly-2018-07-18 -y \
	&& $RUSTUP_HOME/bin/rustup default nightly-2018-07-18 \
	&& mkdir /rust/registry /rust/git
```

It seems that we should install the compiler used by latest TiKV instead of `nightly-2018-07-18`.

**Comment by skyzh** [comment]
cc @zhouqiang-cl

**Comment by zhouqiang-cl** [comment]
Will be fixed in  https://github.com/PingCAP-QE/ci/pull/237
