### ISSUE TITLE
add missing source file in cd pipeline to this repo

### ISSUE THREAD

**Issue by lijie0123** [PingCAP-QE/ci#2445]
metioned in PR: https://github.com/PingCAP-QE/ci/pull/2443
- [ ] upload-pipeline-run-data-to-db: unknown file agent_tibuild_pipeline_run.py // hold
- [ ] send_notify: unknown file agent-jenkinsci.py // hold

metioned in PR: https://github.com/PingCAP-QE/ci/pull/2450
- [x] manifest-multiarch-common: unknown file manifest-tool

gethash: referenced in many pipelines:
- [x] add gethash.py to git
- [ ] refract all pipeline using gethash.py with credential

**Comment by wuhuizuo** [comment]
manifest-tool is a open source tool.

**Comment by wuhuizuo** [comment]
refactored, no need any more.
