### ISSUE TITLE
The packaging and uploading logic of tiup should be consistent between staging & prod

### ISSUE THREAD

**Issue by purelind** [PingCAP-QE/ci#2556]
The package paths of the two environments should normally be consistent.
https://github.com/PingCAP-QE/ci/blob/main/jenkins/pipelines/cd/tiup/tiup-mirror-update-multi-products.groovy#L205-L210

<img width="1302" alt="image" src="https://github.com/PingCAP-QE/ci/assets/16618216/4640fc03-5f65-4acd-bca5-1c25d89adbc7">

**Comment by wuhuizuo** [comment]
we will not fix it in old jenkins groovy, we switched to new CD.
