### ISSUE TITLE
[Dev-Build] support building with FIPS feature

### ISSUE THREAD

**Issue by wuhuizuo** [PingCAP-QE/ci#2606]
## Requirements

Support building binaries and images for these components:

- [x] TiDB `pingcap/tidb`
- [x] TiKV `tikv/tikv`
- [x] PD `tikv/pd`
- [x] TiCDC `pingcap/tiflow`
- [x] BR `pingcap/tidb`
- [x] Dashboard `pingcap/tidb-dashboard`
- [x] Operator `pingcap/tidb-operator`
- [x] Ng-monitoring `pingcap/ng-monitoring`
 
### Go version

go 1.19+ （v6.5.x: 1.19, trunk branches: 1.21)

### How to build
- [x] TiDB `pingcap/tidb`
- [x] TiKV `tikv/tikv`
- [x] PD `tikv/pd`
- [x] TiCDC `pingcap/tiflow`
- [x] BR `pingcap/tidb`
- [x] Dashboard `pingcap/tidb-dashboard`
- [x] Operator `pingcap/tidb-operator`
- [x] Ng-monitoring `pingcap/ng-monitoring`

### Which one is need to change the runtime base images?

- [x] TiKV's base image: https://github.com/tikv/tikv/pull/15944/files#diff-ee3aa9f430cddf671a78d1a6c60b26067bfe2f1c4d6f5be04dd8731fd1474ea5

**Comment by overvenus** [comment]
To build such binary, we can add an env variable "ENABLE_FIPS=1".

E.g.,

PD: `make build` -> `ENABLE_FIPS=1 make build`
TiDB: `make server`  -> `ENABLE_FIPS=1 make server`
TiKV: `ROCKSDB_SYS_STATIC=1 make dist_release` -> `ENABLE_FIPS=1 ROCKSDB_SYS_STATIC=1 make dist_release`

**Comment by lijie0123** [comment]
Is it enough, do we need to change buider image and product image?

**Comment by wuhuizuo** [comment]
Implementation of building logic: https://github.com/PingCAP-QE/ci/pull/2615

**Comment by overvenus** [comment]
We need to support one more project:

* https://github.com/pingcap/ng-monitoring, `ENABLE_FIPS=1 make`

**Comment by wuhuizuo** [comment]
complete tidb-dashboard in https://github.com/PingCAP-QE/ci/pull/2721

**Comment by wuhuizuo** [comment]
tikv runtime dockerfile: https://github.com/PingCAP-QE/artifacts/blob/main/dockerfiles/products/tikv-fips.Dockerfile
