### ISSUE TITLE
advanced-statefulset: add CD pipeline back

### ISSUE THREAD

**Issue by csuzhangxc** [PingCAP-QE/ci#2628]
the previous CD has broken, e.g https://github.com/pingcap/advanced-statefulset/actions/runs/6542217281/job/17764884030

add the CD back, the image can be built with `docker build -t image-tag .` directly

**Comment by wuhuizuo** [comment]
publish:
1. docker.com/pingcap/*
2. clouds registry. @csuzhangxc

**Comment by csuzhangxc** [comment]
> publish:
> 
> 1. docker.com/pingcap/*
> 2. clouds registry. @csuzhangxc

cloud registry:
- ECR: ${account}.dkr.ecr.${region}.amazonaws.com/tidbcloud/advanced-statefulset:${version}
- GCR: gcr.io/pingcap-public/dbaas/advanced-statefulset:${version}

**Comment by wuhuizuo** [comment]
firstly publish to inner registry.
then delivery them to 3 registries:

1. docker.io
2. ECR
3. GCR

**Comment by wuhuizuo** [comment]
disable the broken github action workflow firstly: https://github.com/pingcap/advanced-statefulset/actions/workflows/release.yaml

**Comment by wuhuizuo** [comment]
finished
