### ISSUE TITLE
auto sync from harbor to dockerhub/gcr

### ISSUE THREAD

**Issue by lijie0123** [PingCAP-QE/ci#2763]

**Comment by wuhuizuo** [comment]
We have solved, ref: 
- https://github.com/PingCAP-QE/artifacts/blob/main/packages/delivery.yaml
- https://github.com/PingCAP-QE/ee-ops/blob/544aac941f35911f7e30b86afb72ed61ec165f21/apps/prod/tekton/configs/triggers/triggers/_/image-push-on-harbor.yaml#L54-L79

**Comment by wuhuizuo** [comment]
finished
