### ISSUE TITLE
Replace original CI pipeline in tikv/raft-engine with PingCAP-QE CI

### ISSUE THREAD

**Issue by LykxSassinator** [PingCAP-QE/ci#2935]
## Descriptions
The original CI in [tikv/raft-engine](https://github.com/tikv/raft-engine.git) has limited the space usage of disk, which makes the CI hard to finish and obstruct the development works.

It's expected to replace this CI with PingCAP-QE CI.

**Comment by purelind** [comment]
I will start handle this next week.
